version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"