tap 'neovim/neovim'
tap 'fwdcloudsec/granted'
tap "songmu/tap"

cask "1password"
cask "antigravity-cli"
cask "gather"
cask "orbstack"
cask "slack"
cask 'alacritty'
cask 'ankerwork'
cask 'bitwarden'
cask 'copilot-cli'
cask 'firefox@nightly', args: { language: 'en' }
cask 'font-jetbrains-mono-nerd-font'
cask 'gcloud-cli'
cask 'google-chrome'
cask 'obsidian'
cask 'visual-studio-code'

brew "songmu/tap/ecschedule"
brew 'act'
brew 'actionlint'
brew 'antidote'
brew 'awscli'
brew 'bat'
brew 'carapace'
brew 'chezmoi'
brew 'devcontainer'
brew 'direnv'
brew 'eza'
brew 'fd'
brew 'fwdcloudsec/granted/granted'
brew 'fzf'
brew 'gh'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'gitleaks'
brew 'hadolint'
brew 'jq'
brew 'lefthook'
brew 'mdbook'
brew 'mise'
brew 'neovim'
brew 'pinact'
brew 'ripgrep'
brew 'sops'
brew 'starship'
brew 'stylua'
brew 'tig'
brew 'tmux'
brew 'typos-cli'
