# Common chezmoi data shared across all platforms.

[platform]
name = "common"

[paths]
homebrew_prefix = ""

[packages]
manager = "brew"

[user]
email = "9renpoto@gmail.com"

[github]
user = "9renpoto"

[ssh]
github_identity_file = "~/.ssh/id_ed25519"

[core]
editor = "nvim"
