# This file is a placeholder. chezmoi will use data from this file to
# populate templates. For this repository, you must at least provide
# an email address.
#
# For example:
# email = "your.email@example.com"