set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'hiroppy/tmux-agent-sidebar'

set -g @continuum-restore 'on'

set -g status-bg "colour238"
set -g status-fg "colour255"

set -gq focus-events on
set -sg escape-time 10
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",alacritty:RGB"
set-option -ga terminal-overrides ",tmux-256color:RGB"
set -g set-clipboard on
set -g allow-passthrough on

if-shell 'test -n "$SHELL"' 'set -g default-shell "$SHELL"' 'set -g default-shell "/bin/zsh"'

setw -g window-status-format " #I: #W "
setw -g window-status-current-format "#[fg=colour255,bg=colour27,bold] #I: #W #[default]"

set-window-option -g mode-keys vi

set -g history-limit 999999999

set -g status-right '#{battery_status_bg} Batt: #{battery_percentage} #{battery_remain} #[fg=colour255,bg=colour238]| %a %h-%d %H:%M '
if-shell '[ -x ~/.tmux/plugins/tpm/tpm ]' 'run "~/.tmux/plugins/tpm/tpm"'
