name: chezmoi templates

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: Validate chezmoi configuration
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run chezmoi checks
        run: bash .devcontainer/scripts/check-chezmoi.sh
